version: "3"
services:
    #---------------------------------------------------------------------------

    # Run the test suite in Alpine Linux
    tests-72:
        image: "simplepieng/test-runner:7.2"
        build:
            context: .
            dockerfile: build/tests/Dockerfile-7.2
        volumes:
            - ./:/workspace
        ulimits:
            nofile:
                soft: 65535
                hard: 100000

    # Run the test suite in Alpine Linux with Xdebug enabled for code coverage
    coverage-72:
        image: "simplepieng/test-coverage:7.2"
        build:
            context: .
            dockerfile: build/tests/Dockerfile-7.2-xdebug
        volumes:
            - ./:/workspace
        ulimits:
            nofile:
                soft: 65535
                hard: 100000

    #---------------------------------------------------------------------------

    # Run the test suite in Alpine Linux
    tests-73:
        image: "simplepieng/test-runner:7.3"
        build:
            context: .
            dockerfile: build/tests/Dockerfile-7.3
        volumes:
            - ./:/workspace
        ulimits:
            nofile:
                soft: 65535
                hard: 100000

    # Run the test suite in Alpine Linux with Xdebug enabled for code coverage
    coverage-73:
        image: "simplepieng/test-coverage:7.3"
        build:
            context: .
            dockerfile: build/tests/Dockerfile-7.3-xdebug
        volumes:
            - ./:/workspace
        ulimits:
            nofile:
                soft: 65535
                hard: 100000
